name: Build NDS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install devkitPro
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -S --noconfirm devkitARM libnds

      - name: Build
        run: make

      - name: Upload NDS
        uses: actions/upload-artifact@v4
        with:
          name: nds-build
          path: "*.nds"
